### ISSUE TITLE
Doesn't allow to get tables from Host with key literals

### ISSUE THREAD

**Issue by joelgomes85** [ing-bank/vscode-psl#59] opened 2018-12-14 11:09 UTC
When pulling, for example, UTBLSEX from profile the following error occurs:

[INFO][11:06:15]    … ⇩ UTBLSEX TABLE GET from [environment]
[ERR!][11:06:17]    ✖ ⇩ error in [environment] ER1IOOPEN No such file or directory

This happens with every table with key literals.
This works in Eclipse without errors.

**Comment by atiplea** [comment] 2018-12-14 11:31
The Table Get does a query on DBTBL1D to get the columnList. For UTBLSEX we get:

```
columnList
Array(4) [""SEX"", "DESC", "FMDESC", "SEX"]
```

Then it tries to get the corresponding COL for each element in columnList. Obviously this fails on the first column. The simple solution would be to filter out the literals, agreed?

**Comment by kdrozd** [comment] 2018-12-14 11:32
This table contains two keys one "SEX" - literal, and SEX - first KEY1. 

Only the second one should be downloaded, as literal keys exist in DBTBL1D but should not be used as .COL elements.

**Comment by kdrozd** [comment] 2018-12-14 11:34
> The Table Get does a query on DBTBL1D to get the columnList. For UTBLSEX we get:
> 
> ```
> columnList
> Array(4) [""SEX"", "DESC", "FMDESC", "SEX"]
> ```
> Then it tries to get the corresponding COL for each element in columnList. Obviously this fails on the first column. The simple solution would be to filter out the literals, agreed?

Just handle exception returned by host for columns with literals. it will be like this:
`
FWKINST-E-TYPE,  This column "SEX" should be in table header
`
where `"SEX"` will be replaced by column name.

**Comment by SOliveiraING** [comment] 2022-10-22 11:00
Cannot reproduced in version 1.11.4. seems working, either fixed or something else.

`[INFO][12:56:36]    … ⇩ UTBLSEX TABLE GET from docker

[INFO][12:56:36]    ✔ ⇩ UTBLSEX TABLE GET from docker succeeded`


Closing issue. If still occurring please reopen with details.

**Closed by SOliveiraING** 2022-10-22 11:00 UTC
